#!/usr/bin/env python3
"""png2cg.py - convert bunny sprite sheet frames to CoCo CG3 2bpp sprite data.

Usage: python3 tools/png2cg.py tools/frames.json build

Reads the crop boxes, color map and sequences from frames.json and writes:
  build/sprites.fs    DATA[PY blocks, one per frame, plus a spr lookup word
  build/preview.png   every frame at 4x in CG3 CSS=1 colors, one row per sequence

Sprite record layout (all values in 1x source pixels):
  byte 0  w   width, padded to a multiple of 4
  byte 1  h   height
  byte 2  ox  signed x offset of the left edge from the anchor (always even)
  byte 3  oy  signed y offset of the top edge from the anchor (baseline)
  then ceil(w/4)*h bytes, 2 bits per pixel, MSB first, row by row

The anchor is the centre of the frame's sheet cell on the shared baseline, so
frames of different sizes line up and the hop keeps its lift. ox is kept even
so that at 2x the sprite lands on a byte boundary when the anchor x is a
multiple of 4.
"""

import json
import sys
from pathlib import Path

from PIL import Image, ImageDraw

SCALE = 4          # preview scale
CELL = 40          # preview cell size in 1x pixels
CELL_BASE = 34     # baseline row inside a preview cell


def build_color_map(colors):
    table = {}
    for code, rgbs in colors.items():
        for rgb in rgbs:
            table[tuple(rgb)] = int(code)
    return table


def nearest(rgb, table):
    return min(table.items(),
               key=lambda kv: sum((a - b) ** 2 for a, b in zip(kv[0], rgb)))[1]


def convert_frame(sheet, frame, cfg, table, unmapped):
    x, y, w, h = frame["box"]
    anchor_x = frame["cell_x"] + cfg["cell_w"] // 2
    ox = x - anchor_x
    oy = y - cfg["baseline_y"]
    lead = 0
    if ox % 2:
        ox -= 1
        lead = 1
    pw = w + lead
    pw += (-pw) % 4

    pixels = [[0] * pw for _ in range(h)]
    for yy in range(h):
        for xx in range(w):
            r, g, b, a = sheet.getpixel((x + xx, y + yy))
            if not a:
                continue
            code = table.get((r, g, b))
            if code is None:
                unmapped.add((r, g, b))
                code = nearest((r, g, b), table)
            pixels[yy][lead + xx] = code

    data = bytearray([pw, h, ox & 0xFF, oy & 0xFF])
    for row in pixels:
        for i in range(0, pw, 4):
            c = row[i:i + 4]
            data.append((c[0] << 6) | (c[1] << 4) | (c[2] << 2) | c[3])
    return {"name": frame["name"], "w": pw, "h": h, "ox": ox, "oy": oy,
            "pixels": pixels, "data": bytes(data)}


def double_table():
    table = bytearray()
    for b in range(256):
        p = [(b >> s) & 3 for s in (6, 4, 2, 0)]
        table.append((p[0] << 6) | (p[0] << 4) | (p[1] << 2) | p[1])
        table.append((p[2] << 6) | (p[2] << 4) | (p[3] << 2) | p[3])
    return bytes(table)


def write_forth(path, frames, sequences):
    out = [
        "\\ sprites.fs - generated by tools/png2cg.py from tools/frames.json.",
        "\\ Do not edit. Record: w h ox oy (signed, 1x px from the anchor),",
        "\\ then ceil(w/4)*h bytes of 2bpp pixels, MSB first.",
        "",
    ]
    for f in frames:
        out += [f"DATA[PY spr-{f['name']}",
                f"bytes.fromhex(\"{f['data'].hex()}\")",
                "]DATA", ""]
    out += ["\\ dbl-table - 256 x 16-bit big-endian: each 2bpp byte with every",
            "\\ pixel doubled, for the 2x blitter.",
            "DATA[PY dbl-table",
            f"bytes.fromhex(\"{double_table().hex()}\")",
            "]DATA", ""]
    names = [f["name"] for f in frames]
    out.append(f"{len(frames)} CONSTANT spr-count")
    for seq, members in sequences.items():
        out.append(f"{names.index(members[0])} CONSTANT seq-{seq}")
        out.append(f"{len(members)} CONSTANT seq-{seq}-len")
    out += ["", "\\ spr - frame index (0..spr-count-1) to sprite record address.",
            ": spr  ( n -- addr )"]
    for i, n in enumerate(names[1:], 1):
        out.append(f"  DUP {i} = IF DROP spr-{n} EXIT THEN")
    out += [f"  DROP spr-{names[0]} ;", ""]
    path.write_text("\n".join(out))


def write_preview(path, frames, sequences, cfg):
    rgb = [tuple(c) for c in cfg["preview_rgb"]]
    by_name = {f["name"]: f for f in frames}
    cols = max(len(m) for m in sequences.values())
    # size cells from the frame extents so no frame is clipped
    left = max(-f["ox"] for f in frames) + 2
    cell_w = left + max(f["ox"] + f["w"] for f in frames) + 2
    img = Image.new("RGB", (cols * cell_w * SCALE, len(sequences) * CELL * SCALE), rgb[0])
    draw = ImageDraw.Draw(img)
    for row, members in enumerate(sequences.values()):
        for col, name in enumerate(members):
            f = by_name[name]
            cx = col * cell_w + left
            cy = row * CELL + CELL_BASE
            # baseline and anchor marks, outside the sprite palette on purpose
            draw.line([(col * cell_w * SCALE, cy * SCALE),
                       ((col + 1) * cell_w * SCALE - 1, cy * SCALE)], fill=(225, 210, 160))
            draw.rectangle([cx * SCALE - 1, cy * SCALE, cx * SCALE + 1, cy * SCALE + 6],
                           fill=(200, 40, 40))
            for yy, line in enumerate(f["pixels"]):
                for xx, code in enumerate(line):
                    if code:
                        px = (cx + f["ox"] + xx) * SCALE
                        py = (cy + f["oy"] + yy) * SCALE
                        draw.rectangle([px, py, px + SCALE - 1, py + SCALE - 1], fill=rgb[code])
    img.save(path)


def main():
    if len(sys.argv) != 3:
        sys.exit("usage: png2cg.py frames.json outdir")
    cfg_path = Path(sys.argv[1])
    outdir = Path(sys.argv[2])
    cfg = json.loads(cfg_path.read_text())
    sheet = Image.open(cfg["sheet"]).convert("RGBA")
    table = build_color_map(cfg["colors"])
    unmapped = set()
    frames = [convert_frame(sheet, f, cfg, table, unmapped) for f in cfg["frames"]]

    outdir.mkdir(parents=True, exist_ok=True)
    write_forth(outdir / "sprites.fs", frames, cfg["sequences"])
    write_preview(outdir / "preview.png", frames, cfg["sequences"], cfg)

    total = 0
    for f in frames:
        total += len(f["data"])
        print(f"  {f['name']:8} {f['w']:2}x{f['h']:<2} ox={f['ox']:+3} oy={f['oy']:+3} {len(f['data'])} B")
    print(f"  {len(frames)} frames, {total} B")
    if unmapped:
        print(f"  warning: unmapped colors used nearest match: {sorted(unmapped)}")


if __name__ == "__main__":
    main()
